version: '3.7'

services:
  fastapi:
    build: './fast-api'
    ports: 
      - "8000:8000"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  celery_worker:
    build: './celery_tasks'
    depends_on:
      - rabbitmq
      - fastapi

networks:
  default:
    driver: bridge